baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My New Hugo Project'

disableKinds = ['taxonomy','rss']
defaultContentLanguage = 'fr'
enableRobotsTXT = true
disableHugoGeneratorInject = true
BaseURL = "http://localhost"

[module]
workspace = "../hugo.work"

[[module.imports]]
path = "essai.com/common-hugo-module"


[languages]
_merge = "deep"

[languages.fr]
_merge = "deep"